version: "3.9"
services:
  web:
    build: .
    ports:
      - "2023:2023"
    command: python manage.py runserver 0.0.0.0:2023
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: conceptos_principales
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
